### ISSUE TITLE
Optimizing word_count

### ISSUE THREAD

**Issue by ahmadsherif** [Instabug/nephele#1]
In `Nephele::Cloud#word_count`, `common_words` will be allocated every time the method is called, that's for every word!. Please move it to a constant or make it memoized so it's allocated only once.

**Comment by wazery** [comment]
Thanks Sherif, done.

**Comment by ahmadsherif** [comment]
Actually when you think further into it, you can make it a `Set` instead of an `Array`, since set uses a hash inside, so you'd save yourself some useless iterations, with added bonus of the set responding to `include?`, what do you think?
